#!/usr/bin/env python3
"""
Reads robots.yaml and writes swarm_bridge_config.yaml.
The launch file calls this before starting the bridge node.

Usage:
    python3 generate_bridge_config.py --input config/robots.yaml \
                                      --output config/swarm_bridge_config.yaml
"""

import argparse
import sys
import yaml
from pathlib import Path


def generate(input_path: Path, output_path: Path):
    with open(input_path) as f:
        fleet = yaml.safe_load(f)

    entries = []

    for robot in fleet.get("robots", []):
        name = robot["name"]
        for tpl in fleet.get("bridge_topics", []):
            entries.append({
                "ros_topic_name": tpl["ros_template"].replace("{name}", name),
                "gz_topic_name":  tpl["gz_template"].replace("{name}", name),
                "ros_type_name":  tpl["ros_type"],
                "gz_type_name":   tpl["gz_type"],
                "direction":      tpl["direction"],
            })

    for topic in fleet.get("shared_bridge_topics", []):
        entries.append({
            "ros_topic_name": topic["ros_topic_name"],
            "gz_topic_name":  topic["gz_topic_name"],
            "ros_type_name":  topic["ros_type_name"],
            "gz_type_name":   topic["gz_type_name"],
            "direction":      topic["direction"],
        })

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("# generated by generate_bridge_config.py — edit robots.yaml, not this file\n---\n")
        yaml.dump(entries, f, default_flow_style=False, allow_unicode=True)

    print(f"[bridge_gen] {len(entries)} entries -> {output_path}")
    for e in entries:
        print(f"  {e['direction']:>14}  {e['ros_topic_name']}  <->  {e['gz_topic_name']}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--input",  default="config/robots.yaml")
    p.add_argument("--output", default="config/swarm_bridge_config.yaml")
    args = p.parse_args()

    inp = Path(args.input)
    if not inp.exists():
        print(f"[bridge_gen] not found: {inp}", file=sys.stderr)
        sys.exit(1)

    generate(inp, Path(args.output))

if __name__ == "__main__":
    main()