#!/usr/bin/env python3
"""
generate_bridge_config.py
─────────────────────────
Reads  config/robots.yaml  and writes  config/swarm_bridge_config.yaml
automatically.  Called by the launch file before the bridge node starts,
so you never have to hand-edit the bridge config again.

Usage (standalone):
    python3 generate_bridge_config.py \
        --input  config/robots.yaml \
        --output config/swarm_bridge_config.yaml
"""

import argparse
import sys
import yaml
from pathlib import Path


def generate(input_path: Path, output_path: Path) -> None:
    with open(input_path) as f:
        fleet = yaml.safe_load(f)

    robots         = fleet.get("robots", [])
    bridge_tpls    = fleet.get("bridge_topics", [])
    shared_topics  = fleet.get("shared_bridge_topics", [])

    entries = []

    # ── Per-robot topics ──────────────────────────────────────────────────
    for robot in robots:
        name = robot["name"]
        for tpl in bridge_tpls:
            entries.append({
                "ros_topic_name": tpl["ros_template"].replace("{name}", name),
                "gz_topic_name":  tpl["gz_template"].replace("{name}", name),
                "ros_type_name":  tpl["ros_type"],
                "gz_type_name":   tpl["gz_type"],
                "direction":      tpl["direction"],
            })

    # ── Shared world topics ───────────────────────────────────────────────
    for topic in shared_topics:
        entries.append({
            "ros_topic_name": topic["ros_topic_name"],
            "gz_topic_name":  topic["gz_topic_name"],
            "ros_type_name":  topic["ros_type_name"],
            "gz_type_name":   topic["gz_type_name"],
            "direction":      topic["direction"],
        })

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("# AUTO-GENERATED by generate_bridge_config.py — DO NOT EDIT BY HAND\n")
        f.write("# Edit config/robots.yaml and re-run (or rebuild) to update.\n---\n")
        yaml.dump(entries, f, default_flow_style=False, allow_unicode=True)

    print(f"[bridge_gen] Wrote {len(entries)} bridge entries → {output_path}")
    for e in entries:
        print(f"  {e['direction']:>14}  {e['ros_topic_name']}  ↔  {e['gz_topic_name']}")


def main():
    parser = argparse.ArgumentParser(description="Generate ros_gz_bridge YAML from fleet config")
    parser.add_argument("--input",  default="config/robots.yaml",              help="Fleet config YAML")
    parser.add_argument("--output", default="config/swarm_bridge_config.yaml", help="Output bridge YAML")
    args = parser.parse_args()

    input_path  = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"[bridge_gen] ERROR: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    generate(input_path, output_path)


if __name__ == "__main__":
    main()